// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGBzL9BDIsZ7ga5OD2KCztCj7JHtbifns',
    appId: '1:696548413882:web:af2582d5f2075f9d5b4d83',
    messagingSenderId: '696548413882',
    projectId: 'ptk-plays',
    authDomain: 'ptk-plays.firebaseapp.com',
    storageBucket: 'ptk-plays.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBelRhlDe60HYcK0VxDTu6rH7RoDflHlA0',
    appId: '1:696548413882:android:69a4017791ba067d5b4d83',
    messagingSenderId: '696548413882',
    projectId: 'ptk-plays',
    storageBucket: 'ptk-plays.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKBP7Ng3INwjJucz248tFxefubzxw1hbI',
    appId: '1:696548413882:ios:aea002bbbefe321c5b4d83',
    messagingSenderId: '696548413882',
    projectId: 'ptk-plays',
    storageBucket: 'ptk-plays.firebasestorage.app',
    iosBundleId: 'com.ptksolucoesdigitais.ptkplays',
  );
}
